export enum ActionId {
	AutoSwitchingEnable = 'autoSwitchingEnable',
	AutoSwitchingAudioAList = 'autoSwitchingAudioAList',
	AutoSwitchingAudioBList = 'autoSwitchingAudioBList',
	AutoSwitchingSetAProperties='autoSwitchingSetAProperties',
	AutoSwitchingSetBProperties='autoSwitchingSetBProperties',
	AutoSwitchingAudio = 'autoSwitchingAudio',
	AutoSwitchingAudioThreshold='autoSwitchingAudioThreshold',
	AutoSwitchingAudioSource='autoSwitchingAudioSource',
	AutoSwitchingVideoAMapList = 'autoSwitchingVideoAMapList',
	AutoSwitchingVideoBMapList = 'autoSwitchingVideoBMapList',
	AutoSwitchingVideoABMapList = 'autoSwitchingVideoABMapList',
	AutoSwitchingVideoProperties = 'autoSwitchingVideoProperties',
	AutoSwitchingVideo = 'autoSwitchingVideo',
	AutoSwitchingVideoAMapping='autoSwitchingVideoAMapping',
	AutoSwitchingVideoBMapping='autoSwitchingVideoBMapping',
	AutoSwitchingVideoABMapping='autoSwitchingVideoABMapping',
	AutoSwitchingVideoSwitchingPeriod='autoSwitchingVideoSwitchingPeriod',
	AutoSwitchingVideoABPriority='autoSwitchingVideoABPriority',
}
