export enum ActionId {
	DskEnable = 'dskEnable',
	DskOnAir = 'dskOnAir',
	DSKSourceProperties='dSKSourceProperties',
	DskFillSourceList = 'dskFillSourceList',
	DskFillSource = 'dskFillSource',
	DskKeySourceList = 'dskKeySourceList',
	DskKeySource = 'dskKeySource',
	DSKSetAllProperties='dSKSetAllProperties',
	DskMaskEnable = 'dskMaskEnable',
	DskMaskHStart = 'dskMaskHStart',
	DskMaskVStart = 'dskMaskVStart',
	DskMaskHEnd = 'dskMaskHEnd',
	DskMaskVEnd = 'dskMaskVEnd',
	DskPreMultipliedKey = 'dskPreMultipliedKey',
	DskClip = 'dskClip',
	DskGain = 'dskGain',
	DskInvert = 'dskInvert',
	DskRate = 'dskRate',
	DskResize = 'dskResize',
	DskSizeMinMax = 'dskSizeMinMax',
	DskSize = 'dskSize',
	DskXPosition = 'dskXPosition',
	DskYPosition = 'dskYPosition',
}
