export enum ActionId {
	MultiSourceEnable = 'multiSourceEnable',
	MultiSourceFillSourceList = 'multiSourceFillSourceList',
	MultiSourceFillSource = 'multiSourceFillSource',
	MultiSourceKeySourceList = 'multiSourceKeySourceList',
	MultiSourceKeySource = 'multiSourceKeySource',
	MultiSourcePlaceIn = 'multiSourcePlaceIn',

	MultiSourceControlStyle = 'multiSourceControlStyle',
	MultiSourceWindowBorderWidth = 'multiSourceWindowBorderWidth',
	MultiSourceWindowBorderHue = 'multiSourceWindowBorderHue',
	MultiSourceWindowBorderSaturation = 'multiSourceWindowBorderSaturation',
	MultiSourceWindowBorderBrightness = 'multiSourceWindowBorderBrightness',

	//ISO
	MultiSourceWindowProperties = 'multiSourceWindowProperties',
	MultiSourceWindowSourceList = 'multiSourceWindowSourceList',
	MultiSourceWindowSource = 'multiSourceWindowSource',
	MultiSourceWindowEnable = 'multiSourceWindowEnable',
	MultiSourceWindowXPositionMinMax = 'multiSourceWindowXPositionMinMax',
	MultiSourceWindowXPosition = 'multiSourceWindowXPosition',
	MultiSourceControlYPosition ='multiSourceControlYPosition',
	MultiSourceWindowYPositionMinMax = 'multiSourceWindowYPositionMinMax',
	MultiSourceWindowYPosition = 'multiSourceWindowYPosition',
	MultiSourceWindowSizeMinMax = 'multiSourceWindowSizeMinMax',
	MultiSourceWindowSize = 'multiSourceWindowSize',
	MultiSourceWindowCropEnable = 'multiSourceWindowCropEnable',
	MultiSourceWindowBorderProperties='multiSourceWindowBorderProperties',
	MultiSourceWindowCropLeft = 'multiSourceWindowCropLeft',
	MultiSourceWindowCropRight = 'multiSourceWindowCropRight',
	MultiSourceWindowCropTop = 'multiSourceWindowCropTop',
	MultiSourceWindowCropBottom = 'multiSourceWindowCropBottom',
	MultiSourceWindowCropRadius = 'multiSourceWindowCropRadius',
	MultiSourceWindowCropProperties='multiSourceWindowCropProperties',
}
