export enum ActionId {
	PgmIndex = 'pgmIndex',
	PvwIndex = 'pvwIndex',
	CutTransition = 'cutTransition',
	AutoTransition = 'autoTransition',
	FTB = 'ftb',
	FtbAudioAFV = 'ftbAudioAFV',
	FtbRate = 'ftbRate',
	Prev = 'prev',
	TransitionIndex = 'transitionIndex',
	TransitionRate = 'transitionRate',
	TransitionDipSource = 'transitionDipSource',
	TransitionWipePattern = 'transitionWipePattern',
	TransitionWipeXPosition = 'transitionWipeXPosition',
	TransitionWipeYPosition = 'transitionWipeYPosition',
	TransitionWipeDirection = 'transitionWipeDirection',
	TransitionWipeSymmetry = 'transitionWipeSymmetry',
	TransitionWipeSoftness = 'transitionWipeSoftness',
	TransitionWipeBorder = 'transitionWipeBorder',
	TransitionWipeFillSource = 'transitionWipeFillSource',
	TransitionSourceBG = 'transitionSourceBG',
	TransitionSource = 'transitionSource',
	USKOnPreview = 'uskOnPreview', // This is custom function
	KeyOnAir = 'keyOnAir',
	DskOnAir = 'dskOnAir',
}
