export enum FeedbackId {
	PreviewBG = 'preview_bg',
	PreviewBG2 = 'preview_bg_2',
	PreviewBG3 = 'preview_bg_3',
	PreviewBG4 = 'preview_bg_4',
	ProgramBG = 'program_bg',
	ProgramBG2 = 'program_bg_2',
	ProgramBG3 = 'program_bg_3',
	ProgramBG4 = 'program_bg_4',
	TransitionStyle = 'TransitionStyle',
	InTransition = 'inTransition',
	Cut = 'cut',
	Prev = 'prev',
	TransitionRate = 'transitionRate',
	FadeToBlackIsBlack = 'fadeToBlackIsBlack',
	FadeToBlackRate = 'fadeToBlackRate',
	FTBAFV = 'FTBAFV',
	NextTransitionState = 'transitionSource',
	TransitionSelection = 'transitionSelection',
	TransitionKeySwitch = 'transitionKeySwitch', // @deprecated
	KeyOnAir = 'keyOnAir',
	DskOnAir = 'dskOnAir',
	KeyOnPvw = 'keyOnPvw',
}
