export enum FeedbackId {
	KeyOnAir = 'keyOnAir',
	KeyOnPvw = 'keyOnPvw',
	UpStreamKeyType = 'upStreamKeyType',
	KeySourceFill = 'keySourceFill',
	TransitionSource = 'transitionSource',
	KeyPatternSourceFill = 'keyPatternSourceFill',
	PipSource = 'pipSource',
	PipXPosition = 'pipXPosition',
	PipYPosition = 'pipYPosition',
	KeyPatternResizeSize = 'keyPatternResizeSize',
	KeyPatternResizeXPosition = 'keyPatternResizeXPosition',
	KeyPatternResizeYPosition = 'keyPatternResizeYPosition',
	TransitionKeySwitch = 'transitionKeySwitch',
	TransitionSelection = 'transitionSelection',
}
