export enum ActionId {
	SuperSourceEnable = 'superSourceEnable',
	SuperSourceSource1 = 'superSourceSource1',
	SuperSourceSource2 = 'superSourceSource2',
	SuperSourceBackground = 'superSourceBackground',
	SuperSourceControlStyle = 'superSourceControlStyle',
	SuperSourceControlYPosition = 'superSourceControlYPosition',
	SuperSourceMaskEnable = 'superSourceMaskEnable',
	SuperSourceMaskHStart = 'superSourceMaskHStart',
	SuperSourceMaskVStart = 'superSourceMaskVStart',
	SuperSourceMaskHEnd = 'superSourceMaskHEnd',
	SuperSourceMaskVEnd = 'superSourceMaskVEnd',
	SuperSourceBorderWidth = 'superSourceBorderWidth',
	SuperSourceBorderHue = 'superSourceBorderHue',
	SuperSourceBorderSaturation = 'superSourceBorderSaturation',
	SuperSourceBorderBrightness = 'superSourceBorderBrightness',
}
