export enum ActionId {
	DskSourceFill = 'dskSourceFill',
	DskSourceFillKey = 'dskSourceFillKey',
	DskSourceKey = 'dskSourceKey',
	DskMaskEnable = 'dskMaskEnable',
	DskMaskHStart = 'dskMaskHStart',
	DskMaskVStart = 'dskMaskVStart',
	DskMaskHEnd = 'dskMaskHEnd',
	DskMaskVEnd = 'dskMaskVEnd',
	DskControlShapedKey = 'dskControlShapedKey',
	DskControlClip = 'dskControlClip',
	DskControlGain = 'dskControlGain',
	DskControlInvert = 'dskControlInvert',
	DskRate = 'dskRate',
}
