export enum FeedbackId {
	DskSourceFillKey = 'dskSourceFillKey',
	DskMaskEnable = 'dskMaskEnable',
	DskMaskHStart = 'dskMaskHStart',
	DskMaskVStart = 'dskMaskVStart',
	DskMaskHEnd = 'dskMaskHEnd',
	DskMaskVEnd = 'dskMaskVEnd',
	DskControlShapedKey = 'dskControlShapedKey',
	DskControlClip = 'dskControlClip',
	DskControlGain = 'dskControlGain',
	DskControlInvert = 'dskControlInvert',
	DskRate = 'dskRate',
	DskEnable='dskEnable',
	DskOnAir='dskOnAir',
}
