export enum ActionId {
	PgmIndex = 'pgmIndex',
	PvwIndex = 'pvwIndex',
	//Transition
	CutTransition = 'cutTransition',
	AutoTransition = 'autoTransition',
	FTB = 'ftb',
	FtbAudioAFV = 'ftbAudioAFV',
	FtbRate = 'ftbRate',
	Prev = 'prev',
	TransitionIndex = 'transitionIndex',
	TransitionRate = 'transitionRate',
	TransitionDipSource = 'transitionDipSource',
	//TransitionWipePattern='transitionWipePattern',
	TransitionWipeXPosition = 'transitionWipeXPosition',
	TransitionWipeYPosition = 'transitionWipeYPosition',
	TransitionWipeDirection = 'transitionWipeDirection',
	TransitionWipeSymmetry = 'transitionWipeSymmetry',
	TransitionWipeSoftness = 'transitionWipeSoftness',
	TransitionWipeBorder = 'transitionWipeBorder',
	TransitionWipeFillSource = 'transitionWipeFillSource',
	TransitionPosition = 'transitionPosition',

	//DSK
	TransitionSource = 'transitionSource',
	KeyOnAir = 'keyOnAir',
	DskOnAir = 'dskOnAir',

	DskSourceFill = 'dskSourceFill',
	DskSourceKey = 'dskSourceKey',

	DskMaskEnable = 'dskMaskEnable',
	DskMaskHStart = 'dskMaskHStart',
	DskMaskVStart = 'dskMaskVStart',
	DskMaskHEnd = 'dskMaskHEnd',
	DskMaskVEnd = 'dskMaskVEnd',

	DskControlShapedKey = 'dskControlShapedKey',
	DskControlClip = 'dskControlClip',
	DskControlGain = 'dskControlGain',
	DskControlInvert = 'dskControlInvert',
	DskRate = 'dskRate',

	ColorHue = 'colorHue',
	ColorSaturation = 'colorSaturation',
	ColorBrightness = 'colorBrightness',

	//Super Source
	SuperSourceEnable = 'superSourceEnable',
	SuperSourceSource1 = 'superSourceSource1',
	SuperSourceSource2 = 'superSourceSource2',
	SuperSourceBackground = 'superSourceBackground',
	SuperSourceControlStyle = 'superSourceControlStyle',
	SuperSourceControlYPosition = 'superSourceControlYPosition',
	SuperSourceMaskEnable = 'superSourceMaskEnable',
	SuperSourceMaskHStart = 'superSourceMaskHStart',
	SuperSourceMaskVStart = 'superSourceMaskVStart',
	SuperSourceMaskHEnd = 'superSourceMaskHEnd',
	SuperSourceMaskVEnd = 'superSourceMaskVEnd',
	SuperSourceBorderWidth = 'superSourceBorderWidth',
	SuperSourceBorderHue = 'superSourceBorderHue',
	SuperSourceBorderSaturation = 'superSourceBorderSaturation',
	SuperSourceBorderBrightness = 'superSourceBorderBrightness',

	//UpStream Key
	UpStreamKeyType='upStreamKeyType',
	LumaKeySourceFill='lumaKeySourceFill',
	LumaKeySourceKey='lumaKeySourceKey',
	LumaKeyMaskEnable='lumaKeyMaskEnable',
	LumaKeyMaskHStart='lumaKeyMaskHStart',
	LumaKeyMaskVStart='lumaKeyMaskVStart',
	LumaKeyMaskHEnd='lumaKeyMaskHEnd',
	LumaKeyMaskVEnd='lumaKeyMaskVEnd',
	LumaKeyControlShapedKey='lumaKeyControlShapedKey',
	LumaKeyControlClip='lumaKeyControlClip',
	LumaKeyControlGain='lumaKeyControlGain',
	LumaKeyControlInvert='lumaKeyControlInvert',
	LumaKeyResizeEnable='lumaKeyResizeEnable',
	LumaKeyResizeSize='lumaKeyResizeSize',
	LumaKeyResizeXPosition='lumaKeyResizeXPosition',
	LumaKeyResizeYPosition='lumaKeyResizeYPosition',
	ChromaKeyFill='chromaKeyFill',
	ChromaKeyMaskEnable='chromaKeyMaskEnable',
	ChromaKeyMaskHStart='chromaKeyMaskHStart',
	ChromaKeyMaskVStart='chromaKeyMaskVStart',
	ChromaKeyMaskHEnd='chromaKeyMaskHEnd',
	ChromaKeyMaskVEnd='chromaKeyMaskVEnd',
	ChromaKeyResizeEnable='chromaKeyResizeEnable',
	ChromaKeyResizeSize='chromaKeyResizeSize',
	ChromaKeyResizeXPosition='chromaKeyResizeXPosition',
	ChromaKeyResizeYPosition='chromaKeyResizeYPosition',
	ChromaKeyControlSMPXPosition='chromaKeyControlSMPXPosition',
	ChromaKeyControlSMPYPosition='chromaKeyControlSMPYPosition',
	ChromaKeyControlSample='chromaKeyControlSample',
	ChromaKeyControlColor='chromaKeyControlColor',
	ChromaKeyControlForeground='chromaKeyControlForeground',
	ChromaKeyControlBackground='chromaKeyControlBackground',
	ChromaKeyControlKeyEdge='chromaKeyControlKeyEdge',
	KeyPatternSourceFill='keyPatternSourceFill',
	KeyPatternWipePattern='keyPatternWipePattern',
	KeyPatternWipeSize='keyPatternWipeSize',
	KeyPatternWipeXPosition='keyPatternWipeXPosition',
	KeyPatternWipeYPosition='keyPatternWipeYPosition',
	KeyPatternWipeSymmetry='keyPatternWipeSymmetry',
	KeyPatternWipeSoftness='keyPatternWipeSoftness',
	KeyPatternMaskEnable='keyPatternMaskEnable',
	KeyPatternMaskHStart='keyPatternMaskHStart',
	KeyPatternMaskVStart='keyPatternMaskVStart',
	KeyPatternMaskHEnd='keyPatternMaskHEnd',
	KeyPatternMaskVEnd='keyPatternMaskVEnd',
	KeyPatternResizeEnable='keyPatternResizeEnable',
	KeyPatternResizeSize='keyPatternResizeSize',
	KeyPatternResizeXPosition='keyPatternResizeXPosition',
	KeyPatternResizeYPosition='keyPatternResizeYPosition',
	PipSource='pipSource',
	PipSize='pipSize',
	PipXPosition='pipXPosition',
	PipYPosition='pipYPosition',
	PipMaskEnable='pipMaskEnable',
	PipMaskHStart='pipMaskHStart',
	PipMaskVStart='pipMaskVStart',
	PipMaskHEnd='pipMaskHEnd',
	PipMaskVEnd='pipMaskVEnd',
	PipBorderEnable='pipBorderEnable',
	PipBorderWidth='pipBorderWidth',
	PipBorderHue='pipBorderHue',
	PipBorderSaturation='pipBorderSaturation',
	PipBorderBrightness='pipBorderBrightness',

	//Audio Mixer
	AudioFader='audioFader',
	AudioBalance='audioBalance',
	AudioInput='audioInput',
	AudioEnable='audioEnable',
	AudioDelay='audioDelay',
	AudioMonitorLevel='audioMonitorLevel',
	AudioMonitorSource='audioMonitorSource',

	//Still Generator
	StillSelection='stillSelection',
	StillRemove='stillRemove',
	StillLoadIndex='stillLoadIndex',
	StillLoadImage='stillLoadImage',

	//Macro
	MacroStartRecord='macroStartRecord',
	MacroStopRecord='macroStopRecord',
	MacroChangeDetail='macroChangeDetail',
	MacroDelete='macroDelete',
	MacroLocationSwap='macroLocationSwap',
	MacroStartRun='macroStartRun',
	MacroStopRun='macroStopRun',
	MacroLoop='macroLoop',

	//Streaming
	StreamOutput='streamOutput',
	StreamPlatform='streamPlatform',
	StreamServer='streamServer',
	StreamUrl='streamUrl',

	//Settings
	SrcName='srcName',
	MvMeter='mvMeter',
	MvLayout='mvLayout',
	Marker='marker',
	MicInput='micInput',
	RecordFileName='recordFileName',
	SrcSelection='srcSelection',
	AuxSource='auxSource',
	OutFormat='outFormat',
	OutputColorSpace='outputColorSpace',
	OutSource='outSource',
	NetworkProtocol='networkProtocol',
	NetworkIpAddress='networkIpAddress',
	NetworkSubnetMask='networkSubnetMask',
	NetworkGateway='networkGateway',
	NetworkPrimaryDNS='networkPrimaryDNS',
	NetworkSecondaryDNS='networkSecondaryDNS',
	Quality='quality',
	Panel='panel',
	SdFormat='sdFormat',
	SystemReset='systemReset',

	Record='record',
	RecordStatus='recordStatus',
	RecordTime='recordTime',
	SdCardStatus='sdCardStatus',
	SdFree='sdFree',
	Live='live',
	LiveStatus='liveStatus',
	LiveInfo='liveInfo',
}

export enum ReqType {
	Get = "get",
	Set = "set",
}

export enum ActionType {
	Unknown = 0,
	Heart = 1,
	Program = 2,
	Preview = 3,
	TransitionStyle = 4,
	TransitionDipSource = '5',
	TransitionWipeFillSource = '6',
	DskSourceFill = '7',
	SuperSourceSource = '8',
	LumaKeySourceKey = '9',
	ChromaKeySourceKey = '10',
	KeyPatternSourceKey = '11',
	PipSource='12',
	AudioFader='13',
	AudioMonitorSource='14',
	SettingsoutSource='15',
}

export enum feedbackId {
	PreviewBG = 'preview_bg',
	PreviewBG2 = 'preview_bg_2',
	PreviewBG3 = 'preview_bg_3',
	PreviewBG4 = 'preview_bg_4',
	ProgramBG = 'program_bg',
	ProgramBG2 = 'program_bg_2',
	ProgramBG3 = 'program_bg_3',
	ProgramBG4 = 'program_bg_4',
	TransitionStyle = 'TransitionStyle',
	InTransition = 'inTransition',
	TransitionRate='transitionRate',
	TransitionKeySwitch = 'transitionKeySwitch',
	KeyOnAir = 'keyOnAir',
	DskOnAir = 'dskOnAir',
	SettingOutSource='settingOutSource',
	Macro='macro',
	FadeToBlackIsBlack='fadeToBlackIsBlack',
	FadeToBlackRate='fadeToBlackRate',
	AuxBG='auxBG',
	UpStreamKeyType='upStreamKeyType',
	KeySourceFill='keySourceFill',
}

export enum variableId {
	PlayState = 'playState',
	Clock = 'clock',
	TimerStart = 'timer_start',
	TimerFinish = 'timer_finish',
	TimerDelay = 'timer_delay',
	Time = 'time',
	TimeHM = 'time_hm',
	TimeH = 'time_h',
	TimeM = 'time_m',
	TimeS = 'time_s',
	TitleNow = 'titleNow',
	SubtitleNow = 'subtitleNow',
	SpeakerNow = 'speakerNow',
	NoteNow = 'noteNow',
	TitleNext = 'titleNext',
	SubtitleNext = 'subtitleNext',
	SpeakerNext = 'speakerNext',
	NoteNext = 'noteNext',
	OnAir = 'onAir',
	SpeakerMessage = 'speakerMessage',
	PublicMessage = 'publicMessage',
	LowerMessage = 'lowerMessage',
}

export enum SourceType {
	Input1 = '0',
	Input2 = '1',
	Input3 = '2',
	Input4 = '3',
	Aux = '4',
}

export enum TransitionStyle {
	MIX = '0',
	DIP = '1',
	WIPE = '2',
}
